import { getViteConfig } from 'astro/config';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default (getViteConfig as any)({
  test: {
    globals: true,
    coverage: {
      provider: 'v8',
      include: [
        'src/config/**',
        'src/utils/**',
        'src/scripts/constants.ts',
        'src/scripts/state.ts',
        'src/scripts/analytics.ts',
        'src/scripts/global-stats.ts',
        'src/scripts/theme-switcher.ts',
        'src/scripts/achievements.ts',
        'src/scripts/effects/section-scramble.ts',
        'src/scripts/effects/spotlight.ts',
        'src/scripts/effects/magnetic-nav.ts',
        'src/scripts/effects/favicon.ts',
        'src/scripts/effects/timeline-draw.ts',
        'src/scripts/effects/scroll-terminal.ts',
        'src/scripts/effects/action-log.ts',
        'src/scripts/effects/wireframe.ts',
        'src/scripts/effects/sound.ts',
        'src/scripts/effects/particle-text.ts',
        'src/scripts/effects/code-editor-hero.ts',
        'src/scripts/effects/contribution-3d.ts',
        'src/scripts/effects/toast.ts',
        'src/scripts/effects/typewriter.ts',
        'src/scripts/effects/boot.ts',
        'src/scripts/effects/scramble-text.ts',
        'src/scripts/effects/cursor.ts',
        'src/scripts/effects/hacker-log.ts',
        'src/scripts/effects/hero-name.ts',
        'src/scripts/effects/matrix-rain.ts',
        'src/scripts/effects/screen-effects.ts',
        'src/scripts/dashboard-charts.ts',
        'src/scripts/interactions/copy.ts',
        'src/scripts/interactions/keyboard.ts',
        'src/scripts/interactions/nav.ts',
        'src/scripts/interactions/tilt.ts',
        'src/scripts/interactions/view-more.ts',
        'src/scripts/interactions/blur-up.ts',
        'src/scripts/interactions/floating-icons.ts',
        'src/scripts/interactions/project-cards.ts',
        'src/scripts/interactions/smooth-scroll.ts',
        'src/scripts/interactions/observer.ts',
        'src/scripts/interactions/command-palette.ts',
        'src/scripts/interactions/status-bar.ts',
        'src/scripts/interactions/lang-switcher.ts',
        'src/scripts/interactions/konami.ts',
        'src/scripts/interactions/ctf.ts',
        'src/scripts/interactions/annotations.ts',
        'src/scripts/interactions/achievement-panel.ts',
        'src/scripts/interactions/about-lang.ts',
        'src/scripts/interactions/guestbook-stats.ts',
        'src/scripts/interactions/resume-export.ts',
        'src/scripts/interactions/scroll.ts',
        'src/scripts/utils/focus-trap.ts',
        'src/scripts/pages/terminal.ts',
        'src/scripts/pages/terminal-fs.ts',
        'src/scripts/pages/typing-test.ts',
        'src/scripts/games/breakout.ts',
        'src/scripts/integrations/spotify.ts',
        'src/scripts/integrations/chatbot.ts',
      ],
      thresholds: {
        statements: 60,
        branches: 50,
        functions: 58,
        lines: 60,
        'src/scripts/achievements.ts': {
          statements: 99,
          branches: 98,
          functions: 100,
          lines: 100,
        },
      },
    },
  },
});
