import type { ThemeName } from '../types';

export type TabName = 'main.ts' | 'config.ts' | 'utils.ts';
export const TAB_NAMES: TabName[] = ['main.ts', 'config.ts', 'utils.ts'];

/* ── Per-theme, per-tab code snippets ── */
export const SNIPPETS: Record<ThemeName, Record<TabName, string[]>> = {
  hacker: {
    'main.ts': [
      'const exploit = require("zero-day");',
      'const target = "192.168.1.1";',
      '',
      'async function breach(host) {',
      '  const shell = await exploit.connect(host);',
      '  return shell.escalate("root");',
      '}',
    ],
    'config.ts': [
      'export const config = {',
      '  mode: "stealth",',
      '  encryption: "aes-256",',
      '  proxy: "tor",',
      '  timeout: 30000,',
      '};',
    ],
    'utils.ts': [
      'import crypto from "crypto";',
      '',
      'export function hashPayload(data: string) {',
      '  return crypto',
      '    .createHash("sha256")',
      '    .update(data)',
      '    .digest("hex");',
      '}',
    ],
  },
  dracula: {
    'main.ts': [
      'import { night } from "castle-sdk";',
      '',
      'const coffin = night.awaken({',
      '  bloodType: "#BD93F9",',
      '  immortal: true,',
      '  bats: 42,',
      '});',
    ],
    'config.ts': [
      'export const config = {',
      '  theme: "gothic",',
      '  castle: "transylvania",',
      '  moonPhase: "full",',
      '  garlic: false,',
      '};',
    ],
    'utils.ts': [
      'export function summonBats(count: number) {',
      '  const swarm = [];',
      '  for (let i = 0; i < count; i++) {',
      '    swarm.push({ wing: "left" });',
      '  }',
      '  return swarm;',
      '}',
    ],
  },
  nord: {
    'main.ts': [
      'import { glacier } from "fjord-core";',
      '',
      'const expedition = glacier.plan({',
      '  region: "svalbard",',
      '  temp: -15,',
      '  aurora: true,',
      '});',
    ],
    'config.ts': [
      'export const config = {',
      '  biome: "tundra",',
      '  latitude: 78.2,',
      '  iceDepth: "3km",',
      '  wildlife: ["fox", "bear"],',
      '};',
    ],
    'utils.ts': [
      'export function celsiusToFahr(c: number) {',
      '  return (c * 9) / 5 + 32;',
      '}',
      '',
      'export function windChill(t: number, v: number) {',
      '  return 13.12 + 0.6215 * t - 11.37 * v;',
      '}',
    ],
  },
  catppuccin: {
    'main.ts': [
      'import { brew } from "cozy-sdk";',
      '',
      'const latte = brew({',
      '  blend: "mocha",',
      '  warmth: 0.9,',
      '  foam: true,',
      '});',
    ],
    'config.ts': [
      'export const config = {',
      '  flavor: "macchiato",',
      '  sugar: 2,',
      '  milk: "oat",',
      '  size: "grande",',
      '};',
    ],
    'utils.ts': [
      'export function steep(minutes: number) {',
      '  return new Promise((resolve) => {',
      '    setTimeout(() => {',
      '      resolve({ ready: true });',
      '    }, minutes * 60000);',
      '  });',
      '}',
    ],
  },
  synthwave: {
    'main.ts': [
      'const neon = require("retro-grid");',
      '',
      'async function ignite() {',
      '  const grid = await neon.boot();',
      '  grid.frequency = 98.7;',
      '  return grid.engage("turbo");',
      '}',
    ],
    'config.ts': [
      'export const config = {',
      '  decade: "1980s",',
      '  palette: "neon-pink",',
      '  synth: "moog",',
      '  reverb: 0.85,',
      '};',
    ],
    'utils.ts': [
      'export function generateWaveform(freq: number) {',
      '  const samples = new Float32Array(1024);',
      '  for (let i = 0; i < samples.length; i++) {',
      '    samples[i] = Math.sin(2 * Math.PI * freq * i);',
      '  }',
      '  return samples;',
      '}',
    ],
  },
  matrix: {
    'main.ts': [
      'const construct = require("matrix");',
      '',
      '// There is no spoon.',
      'async function unplug(neo) {',
      '  const pill = await construct.choose();',
      '  if (pill === "red") neo.awaken();',
      '}',
    ],
    'config.ts': [
      'export const config = {',
      '  reality: "simulated",',
      '  exitNode: "hardline",',
      '  agent: "Smith",',
      '  operator: "Tank",',
      '};',
    ],
    'utils.ts': [
      'export function decodeSignal(raw: Buffer) {',
      '  const chars = "ﾊﾐﾋｰｳｼﾅﾓﾆｻﾜﾂｵﾘ";',
      '  let decoded = "";',
      '  for (const byte of raw) {',
      '    decoded += chars[byte % chars.length];',
      '  }',
      '  return decoded;',
      '}',
    ],
  },
  bloodmoon: {
    'main.ts': [
      'import { eclipse } from "crimson";',
      '',
      'const ritual = eclipse.begin({',
      '  phase: "total",',
      '  intensity: 9.8,',
      '  shadow: true,',
      '});',
    ],
    'config.ts': [
      'export const config = {',
      '  omen: "dire",',
      '  tideForce: 12.5,',
      '  color: "#8B0000",',
      '  cycle: "penumbral",',
      '};',
    ],
    'utils.ts': [
      'export function lunarPhase(day: number) {',
      '  const cycle = 29.53;',
      '  const phase = (day % cycle) / cycle;',
      '  if (phase < 0.25) return "waxing";',
      '  if (phase < 0.5) return "full";',
      '  return "waning";',
      '}',
    ],
  },
  midnight: {
    'main.ts': [
      'import { cosmos } from "stellar-sdk";',
      '',
      'const mission = cosmos.launch({',
      '  sector: "andromeda",',
      '  warp: 9,',
      '  shields: true,',
      '});',
    ],
    'config.ts': [
      'export const config = {',
      '  constellation: "orion",',
      '  magnitude: -1.46,',
      '  telescope: "hubble",',
      '  filter: "infrared",',
      '};',
    ],
    'utils.ts': [
      'export function lightYearsToAU(ly: number) {',
      '  return ly * 63241.077;',
      '}',
      '',
      'export function redshift(wavelength: number, v: number) {',
      '  const c = 299792458;',
      '  return wavelength * Math.sqrt((1 + v / c) / (1 - v / c));',
      '}',
    ],
  },
  arctic: {
    'main.ts': [
      'import { env } from "clean-build";',
      '',
      'const config = env.setup({',
      '  mode: "production",',
      '  optimize: true,',
      '  cache: "redis",',
      '});',
    ],
    'config.ts': [
      'export const config = {',
      '  bundler: "vite",',
      '  minify: true,',
      '  sourcemap: false,',
      '  target: "es2022",',
      '};',
    ],
    'utils.ts': [
      'export function formatBytes(bytes: number) {',
      '  const units = ["B", "KB", "MB", "GB"];',
      '  let i = 0;',
      '  while (bytes >= 1024 && i < 3) {',
      '    bytes /= 1024;',
      '    i++;',
      '  }',
      '  return `${bytes.toFixed(1)} ${units[i]}`;',
      '}',
    ],
  },
  gruvbox: {
    'main.ts': [
      'const vim = require("retro-term");',
      '',
      '// :wq',
      'function editConfig(buf) {',
      '  const mode = vim.normal();',
      '  return buf.write(mode);',
      '}',
    ],
    'config.ts': [
      'export const config = {',
      '  editor: "vim",',
      '  colorscheme: "gruvbox",',
      '  tabWidth: 2,',
      '  relativenumber: true,',
      '};',
    ],
    'utils.ts': [
      'export function parseVimRC(lines: string[]) {',
      '  const settings: Record<string, string> = {};',
      '  for (const line of lines) {',
      '    if (line.startsWith("set ")) {',
      '      const [k, v] = line.slice(4).split("=");',
      '      settings[k] = v ?? "true";',
      '    }',
      '  }',
      '  return settings;',
      '}',
    ],
  },
};

/* ── Per-theme, per-tab terminal output ── */
export const TERMINAL_OUTPUT: Record<ThemeName, Record<TabName, { command: string; output: string }>> = {
  hacker: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Shell escalated to root' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Config loaded: stealth mode' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ Hash: 9f86d08...' },
  },
  dracula: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ The count has awakened' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Castle configured' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ 42 bats summoned' },
  },
  nord: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Expedition planned' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Tundra biome loaded' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ -15°C = 5°F' },
  },
  catppuccin: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Latte brewed perfectly' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Macchiato flavor set' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ Steeping for 5 minutes...' },
  },
  synthwave: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Grid engaged at turbo' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Neon palette loaded' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ Waveform generated: 440Hz' },
  },
  matrix: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Neo has been unplugged' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Construct initialized' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ Signal decoded: ﾊﾐﾋｰ...' },
  },
  bloodmoon: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Eclipse ritual complete' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Omen configured: dire' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ Phase: waxing crescent' },
  },
  midnight: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Mission launched' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Telescope: Hubble aligned' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ 4.37 ly = 276,363 AU' },
  },
  arctic: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Build optimized' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Vite config loaded' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ 2.4 MB formatted' },
  },
  gruvbox: {
    'main.ts': { command: '$ ts-node main.ts', output: '✓ Config written' },
    'config.ts': { command: '$ ts-node config.ts', output: '✓ Colorscheme: gruvbox' },
    'utils.ts': { command: '$ ts-node utils.ts', output: '✓ 12 settings parsed' },
  },
};

/* ── Per-theme autocomplete items ── */
export const AUTOCOMPLETE_ITEMS: Record<ThemeName, { icon: string; label: string; detail: string }[]> = {
  hacker: [
    { icon: 'fn', label: 'connect', detail: '(host: string)' },
    { icon: 'fn', label: 'escalate', detail: '(level: string)' },
    { icon: 'var', label: 'target', detail: 'string' },
  ],
  dracula: [
    { icon: 'fn', label: 'awaken', detail: '(opts: Config)' },
    { icon: 'var', label: 'bloodType', detail: 'string' },
    { icon: 'var', label: 'immortal', detail: 'boolean' },
  ],
  nord: [
    { icon: 'fn', label: 'plan', detail: '(opts: Config)' },
    { icon: 'var', label: 'region', detail: 'string' },
    { icon: 'var', label: 'aurora', detail: 'boolean' },
  ],
  catppuccin: [
    { icon: 'fn', label: 'brew', detail: '(opts: Config)' },
    { icon: 'var', label: 'blend', detail: 'string' },
    { icon: 'var', label: 'warmth', detail: 'number' },
  ],
  synthwave: [
    { icon: 'fn', label: 'boot', detail: '()' },
    { icon: 'fn', label: 'engage', detail: '(mode: string)' },
    { icon: 'var', label: 'frequency', detail: 'number' },
  ],
  matrix: [
    { icon: 'fn', label: 'choose', detail: '()' },
    { icon: 'fn', label: 'awaken', detail: '()' },
    { icon: 'var', label: 'pill', detail: 'string' },
  ],
  bloodmoon: [
    { icon: 'fn', label: 'begin', detail: '(opts: Config)' },
    { icon: 'var', label: 'phase', detail: 'string' },
    { icon: 'var', label: 'intensity', detail: 'number' },
  ],
  midnight: [
    { icon: 'fn', label: 'launch', detail: '(opts: Config)' },
    { icon: 'var', label: 'sector', detail: 'string' },
    { icon: 'var', label: 'warp', detail: 'number' },
  ],
  arctic: [
    { icon: 'fn', label: 'setup', detail: '(opts: Config)' },
    { icon: 'var', label: 'mode', detail: 'string' },
    { icon: 'var', label: 'optimize', detail: 'boolean' },
  ],
  gruvbox: [
    { icon: 'fn', label: 'normal', detail: '()' },
    { icon: 'fn', label: 'write', detail: '(mode: Mode)' },
    { icon: 'var', label: 'mode', detail: 'Mode' },
  ],
};
