import type { ThemeName } from '../types';

export type TabName = 'main.js' | 'app.rb' | 'main.py';
export const TAB_NAMES: TabName[] = ['main.js', 'app.rb', 'main.py'];

export const TAB_LANG: Record<TabName, { lang: string; runner: string }> = {
  'main.js': { lang: 'JavaScript', runner: 'node' },
  'app.rb': { lang: 'Ruby', runner: 'ruby' },
  'main.py': { lang: 'Python', runner: 'python3' },
};

/* ── Per-theme, per-tab code snippets ── */
export const SNIPPETS: Record<ThemeName, Record<TabName, string[]>> = {
  hacker: {
    'main.js': [
      'const exploit = require("zero-day");',
      'const target = "192.168.1.1";',
      '',
      'async function breach(host) {',
      '  const shell = await exploit.connect(host);',
      '  return shell.escalate("root");',
      '}',
    ],
    'app.rb': [
      'require "net/ssh"',
      '',
      'class Exploit',
      '  def initialize(target)',
      '    @target = target',
      '  end',
      '',
      '  def breach',
      '    puts "Escalating to root..."',
      '  end',
      'end',
    ],
    'main.py': [
      'import subprocess',
      '',
      'def breach(host):',
      '    shell = connect(host)',
      '    shell.escalate("root")',
      '    return shell',
      '',
      'target = "192.168.1.1"',
    ],
  },
  dracula: {
    'main.js': [
      'import { night } from "castle-sdk";',
      '',
      'const coffin = night.awaken({',
      '  bloodType: "#BD93F9",',
      '  immortal: true,',
      '  bats: 42,',
      '});',
    ],
    'app.rb': [
      'require "castle_sdk"',
      '',
      'coffin = Night.awaken(',
      '  blood_type: "#BD93F9",',
      '  immortal: true,',
      '  bats: 42',
      ')',
    ],
    'main.py': [
      'from castle_sdk import Night',
      '',
      'coffin = Night.awaken(',
      '    blood_type="#BD93F9",',
      '    immortal=True,',
      '    bats=42,',
      ')',
    ],
  },
  nord: {
    'main.js': [
      'import { glacier } from "fjord-core";',
      '',
      'const expedition = glacier.plan({',
      '  region: "svalbard",',
      '  temp: -15,',
      '  aurora: true,',
      '});',
    ],
    'app.rb': [
      'require "fjord_core"',
      '',
      'expedition = Glacier.plan(',
      '  region: "svalbard",',
      '  temp: -15,',
      '  aurora: true',
      ')',
    ],
    'main.py': [
      'from fjord_core import Glacier',
      '',
      'expedition = Glacier.plan(',
      '    region="svalbard",',
      '    temp=-15,',
      '    aurora=True,',
      ')',
    ],
  },
  catppuccin: {
    'main.js': [
      'import { brew } from "cozy-sdk";',
      '',
      'const latte = brew({',
      '  blend: "mocha",',
      '  warmth: 0.9,',
      '  foam: true,',
      '});',
    ],
    'app.rb': [
      'require "cozy_sdk"',
      '',
      'latte = Brew.new(',
      '  blend: "mocha",',
      '  warmth: 0.9,',
      '  foam: true',
      ')',
    ],
    'main.py': [
      'from cozy_sdk import brew',
      '',
      'latte = brew(',
      '    blend="mocha",',
      '    warmth=0.9,',
      '    foam=True,',
      ')',
    ],
  },
  synthwave: {
    'main.js': [
      'const neon = require("retro-grid");',
      '',
      'async function ignite() {',
      '  const grid = await neon.boot();',
      '  grid.frequency = 98.7;',
      '  return grid.engage("turbo");',
      '}',
    ],
    'app.rb': [
      'require "retro_grid"',
      '',
      'def ignite',
      '  grid = Neon.boot',
      '  grid.frequency = 98.7',
      '  grid.engage("turbo")',
      'end',
    ],
    'main.py': [
      'from retro_grid import Neon',
      '',
      'async def ignite():',
      '    grid = await Neon.boot()',
      '    grid.frequency = 98.7',
      '    return grid.engage("turbo")',
    ],
  },
  matrix: {
    'main.js': [
      'const construct = require("matrix");',
      '',
      '// There is no spoon.',
      'async function unplug(neo) {',
      '  const pill = await construct.choose();',
      '  if (pill === "red") neo.awaken();',
      '}',
    ],
    'app.rb': [
      'require "matrix"',
      '',
      '# There is no spoon.',
      'def unplug(neo)',
      '  pill = Construct.choose',
      '  neo.awaken if pill == "red"',
      'end',
    ],
    'main.py': [
      'from matrix import Construct',
      '',
      '# There is no spoon.',
      'def unplug(neo):',
      '    pill = Construct.choose()',
      '    if pill == "red":',
      '        neo.awaken()',
    ],
  },
  bloodmoon: {
    'main.js': [
      'import { eclipse } from "crimson";',
      '',
      'const ritual = eclipse.begin({',
      '  phase: "total",',
      '  intensity: 9.8,',
      '  shadow: true,',
      '});',
    ],
    'app.rb': [
      'require "crimson"',
      '',
      'ritual = Eclipse.begin(',
      '  phase: "total",',
      '  intensity: 9.8,',
      '  shadow: true',
      ')',
    ],
    'main.py': [
      'from crimson import Eclipse',
      '',
      'ritual = Eclipse.begin(',
      '    phase="total",',
      '    intensity=9.8,',
      '    shadow=True,',
      ')',
    ],
  },
  midnight: {
    'main.js': [
      'import { cosmos } from "stellar-sdk";',
      '',
      'const mission = cosmos.launch({',
      '  sector: "andromeda",',
      '  warp: 9,',
      '  shields: true,',
      '});',
    ],
    'app.rb': [
      'require "stellar_sdk"',
      '',
      'mission = Cosmos.launch(',
      '  sector: "andromeda",',
      '  warp: 9,',
      '  shields: true',
      ')',
    ],
    'main.py': [
      'from stellar_sdk import Cosmos',
      '',
      'mission = Cosmos.launch(',
      '    sector="andromeda",',
      '    warp=9,',
      '    shields=True,',
      ')',
    ],
  },
  arctic: {
    'main.js': [
      'import { env } from "clean-build";',
      '',
      'const config = env.setup({',
      '  mode: "production",',
      '  optimize: true,',
      '  cache: "redis",',
      '});',
    ],
    'app.rb': [
      'require "clean_build"',
      '',
      'config = Env.setup(',
      '  mode: "production",',
      '  optimize: true,',
      '  cache: "redis"',
      ')',
    ],
    'main.py': [
      'from clean_build import Env',
      '',
      'config = Env.setup(',
      '    mode="production",',
      '    optimize=True,',
      '    cache="redis",',
      ')',
    ],
  },
  gruvbox: {
    'main.js': [
      'const vim = require("retro-term");',
      '',
      '// :wq',
      'function editConfig(buf) {',
      '  const mode = vim.normal();',
      '  return buf.write(mode);',
      '}',
    ],
    'app.rb': [
      'require "retro_term"',
      '',
      '# :wq',
      'def edit_config(buf)',
      '  mode = Vim.normal',
      '  buf.write(mode)',
      'end',
    ],
    'main.py': [
      'from retro_term import Vim',
      '',
      '# :wq',
      'def edit_config(buf):',
      '    mode = Vim.normal()',
      '    return buf.write(mode)',
    ],
  },
  cyberpunk: {
    'main.js': [
      'const ice = require("netrunner");',
      'const subnet = "arasaka.local";',
      '',
      'async function breach(net) {',
      '  const link = await ice.jack(net);',
      '  return link.quickhack("daemon");',
      '}',
    ],
    'app.rb': [
      'require "netrunner"',
      '',
      'class Quickhack',
      '  def initialize(subnet)',
      '    @subnet = subnet',
      '  end',
    ],
    'main.py': [
      'from netrunner import ICE',
      '',
      'def breach(subnet):',
      '    link = ICE.jack(subnet)',
      '    return link.quickhack("daemon")',
    ],
  },
  nebula: {
    'main.js': [
      'const hubble = require("deep-space");',
      '',
      'async function scan(sector) {',
      '  const signal = await hubble.relay(sector);',
      '  return signal.decode();',
      '}',
    ],
    'app.rb': [
      'require "deep_space"',
      '',
      'def scan(sector)',
      '  signal = Hubble.relay(sector)',
      '  signal.decode',
      'end',
    ],
    'main.py': [
      'from deep_space import Hubble',
      '',
      'def scan(sector):',
      '    signal = Hubble.relay(sector)',
      '    return signal.decode()',
    ],
  },
  solarized: {
    'main.js': [
      'const display = require("solarized");',
      '',
      'function calibrate(opts) {',
      '  const gamma = display.adjust(opts);',
      '  return gamma.apply();',
      '}',
    ],
    'app.rb': [
      'require "solarized"',
      '',
      'def calibrate(opts)',
      '  gamma = Display.adjust(opts)',
      '  gamma.apply',
      'end',
    ],
    'main.py': [
      'from solarized import Display',
      '',
      'def calibrate(opts):',
      '    gamma = Display.adjust(opts)',
      '    return gamma.apply()',
    ],
  },
  rosepine: {
    'main.js': [
      'const garden = require("rose-pine");',
      '',
      'function bloom(season) {',
      '  const petals = garden.grow(season);',
      '  return petals.unfurl();',
      '}',
    ],
    'app.rb': [
      'require "rose_pine"',
      '',
      'def bloom(season)',
      '  petals = Garden.grow(season)',
      '  petals.unfurl',
      'end',
    ],
    'main.py': [
      'from rose_pine import Garden',
      '',
      'def bloom(season):',
      '    petals = Garden.grow(season)',
      '    return petals.unfurl()',
    ],
  },
  monokai: {
    'main.js': [
      'const editor = require("sublime-sdk");',
      '',
      'function highlight(code) {',
      '  const tokens = editor.tokenize(code);',
      '  return tokens.colorize("monokai");',
      '}',
    ],
    'app.rb': [
      'require "sublime_sdk"',
      '',
      'def highlight(code)',
      '  tokens = Editor.tokenize(code)',
      '  tokens.colorize("monokai")',
      'end',
    ],
    'main.py': [
      'from sublime_sdk import Editor',
      '',
      'def highlight(code):',
      '    tokens = Editor.tokenize(code)',
      '    return tokens.colorize("monokai")',
    ],
  },
};

/* ── Per-theme, per-tab terminal output ── */
export const TERMINAL_OUTPUT: Record<
  ThemeName,
  Record<TabName, { command: string; output: string }>
> = {
  hacker: {
    'main.js': { command: '$ node main.js', output: '✓ Shell escalated to root' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Escalating to root...' },
    'main.py': { command: '$ python3 main.py', output: '✓ Shell connected' },
  },
  dracula: {
    'main.js': { command: '$ node main.js', output: '✓ The count has awakened' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Coffin opened' },
    'main.py': { command: '$ python3 main.py', output: '✓ 42 bats summoned' },
  },
  nord: {
    'main.js': { command: '$ node main.js', output: '✓ Expedition planned' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Aurora visible' },
    'main.py': { command: '$ python3 main.py', output: '✓ -15°C = 5°F' },
  },
  catppuccin: {
    'main.js': { command: '$ node main.js', output: '✓ Latte brewed perfectly' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Mocha blend ready' },
    'main.py': { command: '$ python3 main.py', output: '✓ Steeping for 5 minutes...' },
  },
  synthwave: {
    'main.js': { command: '$ node main.js', output: '✓ Grid engaged at turbo' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Neon frequency locked' },
    'main.py': { command: '$ python3 main.py', output: '✓ Waveform generated: 440Hz' },
  },
  matrix: {
    'main.js': { command: '$ node main.js', output: '✓ Neo has been unplugged' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Red pill chosen' },
    'main.py': { command: '$ python3 main.py', output: '✓ Signal decoded: ﾊﾐﾋｰ...' },
  },
  bloodmoon: {
    'main.js': { command: '$ node main.js', output: '✓ Eclipse ritual complete' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Total phase reached' },
    'main.py': { command: '$ python3 main.py', output: '✓ Phase: waxing crescent' },
  },
  midnight: {
    'main.js': { command: '$ node main.js', output: '✓ Mission launched' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Warp drive engaged' },
    'main.py': { command: '$ python3 main.py', output: '✓ 4.37 ly = 276,363 AU' },
  },
  arctic: {
    'main.js': { command: '$ node main.js', output: '✓ Build optimized' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Production mode set' },
    'main.py': { command: '$ python3 main.py', output: '✓ Cache connected' },
  },
  gruvbox: {
    'main.js': { command: '$ node main.js', output: '✓ Config written' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Normal mode active' },
    'main.py': { command: '$ python3 main.py', output: '✓ Buffer saved' },
  },
  cyberpunk: {
    'main.js': { command: '$ node main.js', output: '✓ Daemon uploaded' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Quickhack deployed' },
    'main.py': { command: '$ python3 main.py', output: '✓ ICE breached' },
  },
  nebula: {
    'main.js': { command: '$ node main.js', output: '✓ Signal decoded' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Relay established' },
    'main.py': { command: '$ python3 main.py', output: '✓ Spectrum analyzed' },
  },
  solarized: {
    'main.js': { command: '$ node main.js', output: '✓ Display calibrated' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Gamma applied' },
    'main.py': { command: '$ python3 main.py', output: '✓ Colors balanced' },
  },
  rosepine: {
    'main.js': { command: '$ node main.js', output: '✓ Garden blooming' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Petals unfurled' },
    'main.py': { command: '$ python3 main.py', output: '✓ Season: spring' },
  },
  monokai: {
    'main.js': { command: '$ node main.js', output: '✓ Syntax highlighted' },
    'app.rb': { command: '$ ruby app.rb', output: '✓ Tokens colorized' },
    'main.py': { command: '$ python3 main.py', output: '✓ Build passing' },
  },
};

/* ── Per-theme autocomplete items (JS-flavored for default tab) ── */
export const AUTOCOMPLETE_ITEMS: Record<
  ThemeName,
  { icon: string; label: string; detail: string }[]
> = {
  hacker: [
    { icon: 'fn', label: 'connect', detail: '(host: string)' },
    { icon: 'fn', label: 'escalate', detail: '(level: string)' },
    { icon: 'var', label: 'target', detail: 'string' },
  ],
  dracula: [
    { icon: 'fn', label: 'awaken', detail: '(opts: Config)' },
    { icon: 'var', label: 'bloodType', detail: 'string' },
    { icon: 'var', label: 'immortal', detail: 'boolean' },
  ],
  nord: [
    { icon: 'fn', label: 'plan', detail: '(opts: Config)' },
    { icon: 'var', label: 'region', detail: 'string' },
    { icon: 'var', label: 'aurora', detail: 'boolean' },
  ],
  catppuccin: [
    { icon: 'fn', label: 'brew', detail: '(opts: Config)' },
    { icon: 'var', label: 'blend', detail: 'string' },
    { icon: 'var', label: 'warmth', detail: 'number' },
  ],
  synthwave: [
    { icon: 'fn', label: 'boot', detail: '()' },
    { icon: 'fn', label: 'engage', detail: '(mode: string)' },
    { icon: 'var', label: 'frequency', detail: 'number' },
  ],
  matrix: [
    { icon: 'fn', label: 'choose', detail: '()' },
    { icon: 'fn', label: 'awaken', detail: '()' },
    { icon: 'var', label: 'pill', detail: 'string' },
  ],
  bloodmoon: [
    { icon: 'fn', label: 'begin', detail: '(opts: Config)' },
    { icon: 'var', label: 'phase', detail: 'string' },
    { icon: 'var', label: 'intensity', detail: 'number' },
  ],
  midnight: [
    { icon: 'fn', label: 'launch', detail: '(opts: Config)' },
    { icon: 'var', label: 'sector', detail: 'string' },
    { icon: 'var', label: 'warp', detail: 'number' },
  ],
  arctic: [
    { icon: 'fn', label: 'setup', detail: '(opts: Config)' },
    { icon: 'var', label: 'mode', detail: 'string' },
    { icon: 'var', label: 'optimize', detail: 'boolean' },
  ],
  gruvbox: [
    { icon: 'fn', label: 'normal', detail: '()' },
    { icon: 'fn', label: 'write', detail: '(mode: Mode)' },
    { icon: 'var', label: 'mode', detail: 'Mode' },
  ],
  cyberpunk: [
    { icon: 'fn', label: 'jack', detail: '(net: string)' },
    { icon: 'fn', label: 'quickhack', detail: '(target: string)' },
    { icon: 'var', label: 'subnet', detail: 'string' },
  ],
  nebula: [
    { icon: 'fn', label: 'relay', detail: '(sector: string)' },
    { icon: 'fn', label: 'decode', detail: '()' },
    { icon: 'var', label: 'sector', detail: 'string' },
  ],
  solarized: [
    { icon: 'fn', label: 'adjust', detail: '(opts: Config)' },
    { icon: 'fn', label: 'apply', detail: '()' },
    { icon: 'var', label: 'gamma', detail: 'number' },
  ],
  rosepine: [
    { icon: 'fn', label: 'grow', detail: '(season: string)' },
    { icon: 'fn', label: 'unfurl', detail: '()' },
    { icon: 'var', label: 'season', detail: 'string' },
  ],
  monokai: [
    { icon: 'fn', label: 'tokenize', detail: '(code: string)' },
    { icon: 'fn', label: 'colorize', detail: '(scheme: string)' },
    { icon: 'var', label: 'theme', detail: 'string' },
  ],
};

/* ── Sidebar panel data ── */
export const GIT_STATUS = [
  'On branch main',
  '',
  'Changes not staged:',
  '  modified: main.js',
  '',
  'Untracked:',
  '  .env.local',
];

export const EXTENSIONS_LIST: [string, string][] = [
  ['ESLint', 'v2.4.2'],
  ['Prettier', 'v10.1.0'],
  ['GitLens', 'v14.5.0'],
  ['Ruby LSP', 'v0.14.1'],
];

export const SETTINGS_PAIRS: [string, string][] = [
  ['editor.fontSize', '14'],
  ['editor.tabSize', '2'],
  ['editor.wordWrap', 'on'],
  ['terminal.fontSize', '13'],
];
