import { getClientIP, getCurrentTheme } from './state';
import type {
  AboutTheme,
  AnalyticsThemeMap,
  BootMessage,
  StatusBarConfig,
  ThemeConfig,
  ThemeName,
  ThemeToasts,
} from './types';

export { getCurrentTheme } from './state';

function themeGetter<T>(map: Record<ThemeName, T>): (theme?: ThemeName) => T {
  return (theme) => map[theme ?? getCurrentTheme()] ?? map.hacker;
}

export const themeLogos: Record<ThemeName, { text: string; suffix: string }> = {
  hacker: { text: 'fyniti', suffix: '://hk' },
  dracula: { text: 'fyniti', suffix: '::hk' },
  nord: { text: 'fyniti', suffix: '.hk' },
  catppuccin: { text: 'fyniti', suffix: '~/hk' },
  synthwave: { text: 'fyniti', suffix: '>>hk' },
  matrix: { text: 'fyniti', suffix: '/hk' },
  bloodmoon: { text: 'fyniti', suffix: '#hk' },
  midnight: { text: 'fyniti', suffix: '@hk' },
  arctic: { text: 'fyniti', suffix: '.hk' },
  gruvbox: { text: 'fyniti', suffix: '\\hk' },
};

export const themePrompts: Record<ThemeName, string> = {
  hacker: 'root@kali:~# whoami',
  dracula: 'dracula@castle:~$ whoami',
  nord: 'user@fjord:~$ whoami',
  catppuccin: 'neko@mocha:~$ whoami',
  synthwave: 'dj@neonGrid:~$ whoami',
  matrix: 'neo@matrix:~# whoami',
  bloodmoon: 'hunter@eclipse:~# whoami',
  midnight: 'astro@nebula:~$ whoami',
  arctic: 'dev@glacier:~$ whoami',
  gruvbox: 'user@retro:~$ whoami',
};

export const themeTypewriterTexts: Record<ThemeName, string[]> = {
  hacker: [
    '> Senior Software Engineer',
    '> Bypassing firewall protocols...',
    '> Ruby on Rails — exploit deployed',
    '> Node.js injection payload ready',
    '> React components compromised',
    '> AWS infrastructure infiltrated',
    '> PostgreSQL data exfiltrated',
    '> Docker containers breached',
    '> GraphQL schema enumerated',
    '> TypeScript zero-day compiled',
    '> Redis cache poisoned',
    '> Open source rootkits published',
    '> Access granted. Welcome back.',
  ],
  dracula: [
    '> Senior Software Engineer',
    '> The mass darkness stirs...',
    '> Ruby on Rails — immortal framework',
    '> Node.js event loop never sleeps',
    '> React — reborn with every render',
    '> AWS clouds part for the count',
    '> PostgreSQL — eternal data vault',
    '> Docker coffins sealed tight',
    '> GraphQL queries from the crypt',
    '> TypeScript — type-safe in the dark',
    '> Redis — blood-red cache layer',
    '> Open source from Transylvania',
    '> The count welcomes you.',
  ],
  nord: [
    '> Senior Software Engineer',
    '> Calm as the northern fjords...',
    '> Ruby on Rails — steady as the fjords',
    '> Node.js streams flow like glacial rivers',
    '> React — minimal, purposeful UI',
    '> AWS — aurora-lit infrastructure',
    '> PostgreSQL — frozen solid data',
    '> Docker — containerized serenity',
    '> GraphQL — clean, structured queries',
    '> TypeScript — precise and composed',
    '> Redis — swift as polar winds',
    '> Open source from the quiet north',
    '> Welcome to the quiet north.',
  ],
  catppuccin: [
    '> Senior Software Engineer',
    '> Brewing something warm~',
    '> Ruby on Rails with a warm latte~',
    '> Node.js — sweet async treats',
    '> React — cozy component library',
    '> AWS — cloud-soft infrastructure~',
    '> PostgreSQL — freshly roasted data',
    '> Docker — neatly packed bento boxes',
    '> GraphQL — a perfectly layered cake',
    '> TypeScript — types with sprinkles~',
    '> Redis — quick espresso cache',
    '> Open source with love and pastels',
    '> Pull up a chair, stay a while~',
  ],
  synthwave: [
    '> Senior Software Engineer',
    '> Booting neon grid sequence...',
    '> Ruby on Rails at light speed',
    '> Node.js at 88 miles per hour',
    '> React — rendering the retro future',
    '> AWS — neon-lit cloud highways',
    '> PostgreSQL — data in the fast lane',
    '> Docker — chrome-plated containers',
    '> GraphQL — laser-guided queries',
    '> TypeScript — synth-typed perfection',
    '> Redis — turbo-cached at 120bpm',
    '> Open source from the neon arcade',
    '> Welcome to the grid, rider.',
  ],
  matrix: [
    '> Senior Software Engineer',
    '> Wake up... the code has you.',
    '> Ruby on Rails — follow the white rabbit',
    '> Node.js — there is no callback',
    '> React — the construct is loading',
    '> AWS — the machine city awaits',
    '> PostgreSQL — the Oracle knows',
    '> Docker — pods in the Matrix',
    '> GraphQL — querying the source code',
    '> TypeScript — the One true type system',
    '> Redis — red pill cache activated',
    '> Open source — free your mind',
    '> There is no spoon. Only functions.',
  ],
  bloodmoon: [
    '> Senior Software Engineer',
    '> The hunt for perfect code begins...',
    '> Ruby on Rails — forged in crimson fire',
    '> Node.js — relentless event predator',
    '> React — components sharp as fangs',
    '> AWS — infrastructure under blood skies',
    '> PostgreSQL — data sealed in obsidian',
    '> Docker — hunting in packs',
    '> GraphQL — tracking every query',
    '> TypeScript — precision of the kill',
    '> Redis — bloodhound-fast cache',
    '> Open source — unleash the pack',
    '> The eclipse reveals all.',
  ],
  midnight: [
    '> Senior Software Engineer',
    '> Charting the code nebula...',
    '> Ruby on Rails — orbiting at warp speed',
    '> Node.js — signals from deep space',
    '> React — rendering distant galaxies',
    '> AWS — cosmic cloud infrastructure',
    '> PostgreSQL — stellar data clusters',
    '> Docker — orbital containers deployed',
    '> GraphQL — scanning the star charts',
    '> TypeScript — astro-typed precision',
    '> Redis — light-speed cache relay',
    '> Open source across the galaxy',
    '> Transmission received. Welcome aboard.',
  ],
  arctic: [
    '> Senior Software Engineer',
    '> Initializing clean workspace...',
    '> Ruby on Rails — clean, reliable, fast',
    '> Node.js — efficient async workflows',
    '> React — modular component architecture',
    '> AWS — scalable cloud solutions',
    '> PostgreSQL — robust data management',
    '> Docker — reproducible environments',
    '> GraphQL — precise API design',
    '> TypeScript — enterprise-grade types',
    '> Redis — high-performance caching',
    '> Open source — community-driven code',
    "> Welcome. Let's build something great.",
  ],
  gruvbox: [
    '> Senior Software Engineer',
    '> Booting vintage terminal...',
    '> Ruby on Rails — classic and battle-tested',
    '> Node.js — old reliable, new tricks',
    '> React — components from the golden age',
    '> AWS — mainframe-grade cloud power',
    "> PostgreSQL — rock-solid since '96",
    '> Docker — containers, the unix way',
    '> GraphQL — querying like a sysadmin',
    '> TypeScript — strongly typed, old school',
    '> Redis — cache at the speed of CRT',
    '> Open source — the hacker ethic lives',
    '> Connection established. Welcome back.',
  ],
};

// LeetCode custom colors format: bg0,bg1,text0,text1,color0,color1,color2,color3 (hex without #)
export const analyticsThemeMap: Record<ThemeName, AnalyticsThemeMap> = {
  hacker: {
    stats: 'tokyonight',
    summary: 'tokyonight',
    trophy: 'tokyonight',
    streakBg: '0D1117',
    activityTheme: 'tokyo-night',
    leetcodeTheme: 'dark',
    leetcodeColors: '0D1117,161B22,FFFFFF,8B949E,5BCDEC,58A6FF,3FB950,00BFA5',
    stackoverflowTheme: 'dark',
  },
  dracula: {
    stats: 'dracula',
    summary: 'dracula',
    trophy: 'dracula',
    streakBg: '282A36',
    activityTheme: 'dracula',
    leetcodeTheme: 'dark',
    leetcodeColors: '282A36,44475A,F8F8F2,6272A4,BD93F9,FF79C6,50FA7B,8BE9FD',
    stackoverflowTheme: 'dark',
  },
  nord: {
    stats: 'nord',
    summary: 'nord_dark',
    trophy: 'nord',
    streakBg: '2E3440',
    activityTheme: 'nord',
    leetcodeTheme: 'nord',
    leetcodeColors: '2E3440,3B4252,ECEFF4,D8DEE9,88C0D0,81A1C1,A3BE8C,B48EAD',
    stackoverflowTheme: 'dark',
  },
  catppuccin: {
    stats: 'catppuccin_mocha',
    summary: 'dracula',
    trophy: 'aura',
    streakBg: '1E1E2E',
    activityTheme: 'tokyo-night',
    leetcodeTheme: 'dark',
    leetcodeColors: '1E1E2E,313244,CDD6F4,A6ADC8,CBA6F7,F38BA8,A6E3A1,89DCEB',
    stackoverflowTheme: 'dark',
  },
  synthwave: {
    stats: 'synthwave',
    summary: 'radical',
    trophy: 'radical',
    streakBg: '1A1028',
    activityTheme: 'synthwave-84',
    leetcodeTheme: 'unicorn',
    leetcodeColors: '1A1028,241734,F0E6FF,B894E0,FF2E97,FF6EC7,FCEE09,00F0FF',
    stackoverflowTheme: 'dark',
  },
  matrix: {
    stats: 'dark',
    summary: 'tokyonight',
    trophy: 'matrix',
    streakBg: '0A0A0A',
    activityTheme: 'green',
    leetcodeTheme: 'forest',
    leetcodeColors: '0A0A0A,111111,00FF41,33CC33,00FF41,00CC33,009926,66FF66',
    stackoverflowTheme: 'dark',
  },
  bloodmoon: {
    stats: 'radical',
    summary: 'radical',
    trophy: 'radical',
    streakBg: '0D0208',
    activityTheme: 'coral',
    leetcodeTheme: 'dark',
    leetcodeColors: '0D0208,1A0510,FFFFFF,8B7070,FF0040,FF4D6D,C9184A,FF758F',
    stackoverflowTheme: 'dark',
  },
  midnight: {
    stats: 'shades-of-purple',
    summary: '2077',
    trophy: 'onestar',
    streakBg: '0F0F1A',
    activityTheme: 'material-palenight',
    leetcodeTheme: 'dark',
    leetcodeColors: '0F0F1A,1A1A2E,FFFFFF,8888AA,7B73FF,9B93FF,5C55CC,B0ADFF',
    stackoverflowTheme: 'dark',
  },
  arctic: {
    stats: 'graywhite',
    summary: 'default',
    trophy: 'flat',
    streakBg: 'F0F9FF',
    activityTheme: 'arctic',
    leetcodeTheme: 'light',
    leetcodeColors: 'F0F9FF,E0F2FE,0C4A6E,475569,0369A1,0284C7,0EA5E9,38BDF8',
    stackoverflowTheme: 'light',
  },
  gruvbox: {
    stats: 'gruvbox',
    summary: 'gruvbox',
    trophy: 'gruvbox',
    streakBg: '282828',
    activityTheme: 'gruvbox',
    leetcodeTheme: 'dark',
    leetcodeColors: '282828,3C3836,EBDBB2,A89984,FABD2F,FE8019,B8BB26,83A598',
    stackoverflowTheme: 'dark',
  },
};

function formatUptime(elapsed: number): string {
  const h = Math.floor(elapsed / 3600);
  const m = Math.floor((elapsed % 3600) / 60);
  const s = elapsed % 60;
  return `${h < 10 ? '0' : ''}${h}:${m < 10 ? '0' : ''}${m}:${s < 10 ? '0' : ''}${s}`;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export const themeStatusBars: Record<ThemeName, StatusBarConfig> = {
  hacker: [
    { label: '\u25C9 SECURE CONNECTION', cls: 'status-secure' },
    { label: 'IP: ', value: () => getClientIP() || '...' },
    {
      label: '',
      value: () =>
        `\u2191 ${(Math.random() * 36 + 12).toFixed(1)} MB/s \u2193 ${(Math.random() * 75 + 45).toFixed(1)} MB/s`,
    },
    { label: '', value: () => `${Math.floor(Math.random() * 10 + 18)} PROCESSES` },
    { label: 'UPTIME: ', value: (e) => formatUptime(e) },
  ],
  dracula: [
    { label: '\u25C9 NOCTURNAL MODE', cls: 'status-secure' },
    { label: 'BLOOD TYPE: #BD93F9' },
    { label: 'MOON: ', value: () => pick(['FULL', 'WANING', 'NEW', 'CRESCENT', 'BLOOD']) },
    { label: '', value: () => `${Math.floor(Math.random() * 50 + 10)} COFFINS SEALED` },
    { label: 'NIGHT CYCLE: ', value: (e) => formatUptime(e) },
  ],
  nord: [
    { label: '\u25C9 POLAR STATION', cls: 'status-secure' },
    { label: 'REGION: SVALBARD' },
    { label: 'TEMP: ', value: () => `${(-Math.random() * 30 - 5).toFixed(1)}\u00B0C` },
    { label: 'AURORA: ', value: () => `${Math.floor(Math.random() * 10 + 1)}/10` },
    { label: 'WIND: ', value: () => `${(Math.random() * 60 + 5).toFixed(0)} km/h` },
  ],
  catppuccin: [
    { label: '\u25C9 COZY MODE', cls: 'status-secure' },
    { label: 'BLEND: MOCHA' },
    { label: 'BREW: ', value: () => pick(['STEEPING', 'READY', 'POURING', 'FRESH', 'PERFECT']) },
    { label: 'WARMTH: ', value: () => `${Math.floor(Math.random() * 30 + 70)}%` },
    { label: 'COMFORT: ', value: (e) => formatUptime(e) },
  ],
  synthwave: [
    { label: '\u25C9 NEON GRID ONLINE', cls: 'status-secure' },
    { label: 'FM 98.7' },
    { label: 'FREQ: ', value: () => `${(Math.random() * 2000 + 200).toFixed(0)} Hz` },
    { label: 'SIGNAL: ', value: () => `${Math.floor(Math.random() * 10 + 1)}/10` },
    {
      label: 'TAPE: ',
      value: () => pick(['PLAYING', 'REWINDING', 'SIDE A', 'SIDE B', 'RECORDING']),
    },
  ],
  matrix: [
    { label: '\u25C9 SIMULATION ACTIVE', cls: 'status-secure' },
    { label: 'NODE: ', value: () => getClientIP() || '...' },
    { label: 'TICK: ', value: () => `#${Math.floor(Math.random() * 99999)}` },
    { label: '', value: () => `${Math.floor(Math.random() * 8 + 1)} AGENTS DETECTED` },
    { label: 'SIGNAL: ', value: () => `${Math.floor(Math.random() * 40 + 60)}%` },
  ],
  bloodmoon: [
    { label: '\u25C9 CRIMSON PROTOCOL', cls: 'status-secure' },
    { label: 'COVENANT: ACTIVE' },
    {
      label: 'ECLIPSE: ',
      value: () => pick(['TOTAL', 'PARTIAL', 'PENUMBRAL', 'WAXING', 'PEAK']),
    },
    { label: 'CRIMSON: ', value: () => `${(Math.random() * 9 + 1).toFixed(1)}` },
    { label: 'SHADOWS: ', value: () => `${Math.floor(Math.random() * 100 + 1)} DEEP` },
  ],
  midnight: [
    { label: '\u25C9 DEEP SPACE RELAY', cls: 'status-secure' },
    { label: 'SECTOR: ANDROMEDA' },
    { label: '', value: () => `${Math.floor(Math.random() * 9000 + 1000)} STARS MAPPED` },
    { label: 'NEBULA: ', value: () => `${(Math.random() * 500 + 10).toFixed(1)} ly` },
    { label: 'ORBIT: ', value: (e) => formatUptime(e) },
  ],
  arctic: [
    { label: '\u25C9 STATION ONLINE', cls: 'status-secure' },
    { label: 'ENV: CLEAN' },
    { label: 'TEMP: ', value: () => `${(-Math.random() * 15 - 1).toFixed(1)}\u00B0C` },
    { label: 'VISIBILITY: ', value: () => `${Math.floor(Math.random() * 30 + 70)}%` },
    { label: 'ICE: ', value: () => `${Math.floor(Math.random() * 15 + 85)}% INTEGRITY` },
  ],
  gruvbox: [
    { label: '\u25C9 VIM READY', cls: 'status-secure' },
    { label: 'NORMAL' },
    { label: '', value: () => `${Math.floor(Math.random() * 12 + 1)} BUF OPEN` },
    { label: 'TERM: ', value: () => pick(['zsh', 'bash', 'fish', 'tmux', 'screen']) },
    { label: ':w ', value: (e) => formatUptime(e) },
  ],
};

const baseTheme: ThemeConfig = {
  canvasEffect: 'particles',
  hasMatrixRain: false,
  hasCRT: false,
  screenEffect: 'none',
  hasHackerLog: false,
  hasCursor: false,
  particleColor: 'rgba(255, 255, 255, ',
  bootBg: '#0a0e14',
  navBg: 'transparent',
  heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  heroTiming: { flicker: 60, resolve: 110 },
};

export const themeConfig: Record<ThemeName, ThemeConfig> = {
  hacker: {
    ...baseTheme,
    hasMatrixRain: true,
    hasCRT: true,
    screenEffect: 'glitch',
    hasHackerLog: true,
    hasCursor: 'crosshair',
    particleColor: 'rgba(91, 205, 236, ',
    matrixColor: 'rgba(0, 191, 191, 0.6)',
    matrixBg: 'rgba(10, 14, 20, 0.06)',
    navBg: 'rgba(13, 17, 23, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789$@#!%&*?',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  dracula: {
    ...baseTheme,
    canvasEffect: 'purpleParticles',
    screenEffect: 'fogWisps',
    hasCursor: 'dot',
    particleColor: 'rgba(189, 147, 249, ',
    bootBg: '#1e1b2e',
    navBg: 'rgba(40, 42, 54, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ†‡§¶∞ΩΨ',
  },
  nord: {
    ...baseTheme,
    canvasEffect: 'snowfall',
    screenEffect: 'auroraShimmer',
    particleColor: 'rgba(136, 192, 208, ',
    bootBg: '#242933',
    navBg: 'rgba(46, 52, 64, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ·:;_=-~',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  catppuccin: {
    ...baseTheme,
    canvasEffect: 'bubbles',
    screenEffect: 'pastelBloom',
    hasCursor: 'dot',
    particleColor: 'rgba(203, 166, 247, ',
    bootBg: '#181825',
    navBg: 'rgba(30, 30, 46, ',
    heroGlyphs: 'abcdefghijklmnopqrstuvwxyz~*.:+',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  synthwave: {
    ...baseTheme,
    canvasEffect: 'retroGrid',
    hasCRT: true,
    screenEffect: 'vhsDistortion',
    hasCursor: 'dot',
    particleColor: 'rgba(255, 46, 151, ',
    bootBg: '#120a1e',
    navBg: 'rgba(26, 16, 40, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ▓░▒█01',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  matrix: {
    ...baseTheme,
    hasMatrixRain: true,
    hasCRT: true,
    screenEffect: 'glitch',
    hasCursor: 'crosshair',
    particleColor: 'rgba(0, 255, 65, ',
    matrixColor: 'rgba(0, 255, 65, 0.8)',
    matrixBg: 'rgba(0, 0, 0, 0.05)',
    bootBg: '#050505',
    navBg: 'rgba(10, 10, 10, ',
    heroGlyphs: 'アイウエオカキクケコサシスセソ01',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  bloodmoon: {
    ...baseTheme,
    canvasEffect: 'bloodRain',
    screenEffect: 'bloodDrip',
    hasCursor: 'dot',
    particleColor: 'rgba(255, 0, 64, ',
    bootBg: '#080104',
    navBg: 'rgba(13, 2, 8, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ†‡Ψ∞Ω◆',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  midnight: {
    ...baseTheme,
    canvasEffect: 'starfield',
    screenEffect: 'shootingStar',
    particleColor: 'rgba(123, 115, 255, ',
    bootBg: '#0a0a12',
    navBg: 'rgba(15, 15, 26, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ★✦⊹∗⋆',
  },
  arctic: {
    ...baseTheme,
    canvasEffect: 'lightDust',
    screenEffect: 'iceCrack',
    particleColor: 'rgba(3, 105, 161, ',
    bootBg: '#e0f2fe',
    navBg: 'rgba(219, 234, 254, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  gruvbox: {
    ...baseTheme,
    canvasEffect: 'fireflies',
    screenEffect: 'tvStatic',
    hasCRT: true,
    hasCursor: 'dot',
    particleColor: 'rgba(250, 189, 47, ',
    bootBg: '#1d2021',
    navBg: 'rgba(40, 40, 40, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ>|/-_=+[]',
  },
};

export const bootMessages: Record<ThemeName, BootMessage[]> = {
  hacker: [
    { text: '$ uname -a', cls: 'boot-cmd' },
    {
      text: 'Linux mainframe 6.1.0-kali9 #1 SMP x86_64 GNU/Linux',
      cls: 'boot-output',
    },
    {
      text: '$ sudo systemctl start portfolio.service',
      cls: 'boot-cmd',
    },
    { text: '[  OK  ] Started portfolio.service', cls: 'boot-ok' },
    { text: '$ nmap -sS 10.0.0.0/24 --top-ports 5', cls: 'boot-cmd' },
    {
      text: 'Starting Nmap 7.94 ( https://nmap.org )',
      cls: 'boot-output',
    },
    { text: 'PORT    STATE SERVICE', cls: 'boot-output' },
    { text: '22/tcp  open  ssh', cls: 'boot-output' },
    { text: '80/tcp  open  http', cls: 'boot-output' },
    { text: '443/tcp open  https', cls: 'boot-output' },
    {
      text: '$ ssh -i ~/.ssh/id_rsa root@portfolio',
      cls: 'boot-cmd',
    },
    { text: 'Authenticating with public key...', cls: 'boot-output' },
    { text: 'root@portfolio:~# cat /etc/motd', cls: 'boot-cmd' },
    { text: '', cls: '' },
  ],
  dracula: [
    { text: '> Awakening from coffin...', cls: 'boot-cmd' },
    { text: 'Blood type: #BD93F9', cls: 'boot-output' },
    { text: '> Loading nocturnal protocols...', cls: 'boot-cmd' },
    { text: '[  OK  ] Bat signal initialized', cls: 'boot-ok' },
    { text: '> Checking garlic firewall...', cls: 'boot-cmd' },
    { text: 'No threats detected', cls: 'boot-output' },
    { text: '> Moon phase: Full', cls: 'boot-output' },
    { text: '> Vampire.js runtime loaded', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  nord: [
    { text: '> Initializing aurora...', cls: 'boot-cmd' },
    { text: 'Polar winds calibrated', cls: 'boot-output' },
    { text: '> Loading frost interface...', cls: 'boot-cmd' },
    { text: '[  OK  ] Nordic shell ready', cls: 'boot-ok' },
    { text: '> Temperature: -15C', cls: 'boot-output' },
    { text: '> Snowfall density: optimal', cls: 'boot-output' },
    { text: '> Ice core sample analyzed', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  catppuccin: [
    { text: '> Brewing fresh mocha...', cls: 'boot-cmd' },
    { text: 'Warming up the pixels', cls: 'boot-output' },
    { text: '> Loading cozy interface...', cls: 'boot-cmd' },
    { text: '[  OK  ] Comfort mode engaged', cls: 'boot-ok' },
    { text: '> Latte foam: perfect', cls: 'boot-output' },
    { text: '> Ambient warmth: 100%', cls: 'boot-output' },
    { text: '> Pastel palette loaded', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  synthwave: [
    { text: 'LOADING CASSETTE...', cls: 'boot-cmd' },
    { text: '> PLAY SIDE A', cls: 'boot-output' },
    { text: 'NEON SYSTEMS ONLINE', cls: 'boot-ok' },
    { text: '> Retrowave frequency locked', cls: 'boot-output' },
    {
      text: '> DeLorean flux capacitor: READY',
      cls: 'boot-output',
    },
    { text: '> Synthesizer calibrated', cls: 'boot-output' },
    { text: '> Chrome reflections: MAX', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  matrix: [
    { text: 'Wake up, Neo...', cls: 'boot-cmd' },
    { text: 'The Matrix has you...', cls: 'boot-output' },
    { text: 'Follow the white rabbit.', cls: 'boot-output' },
    { text: '> Knock, knock.', cls: 'boot-cmd' },
    { text: 'Loading construct...', cls: 'boot-output' },
    { text: '[  OK  ] Red pill accepted', cls: 'boot-ok' },
    { text: '> Agent detection: scanning', cls: 'boot-output' },
    { text: '> Zion mainframe connected', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  bloodmoon: [
    { text: '> Eclipse detected...', cls: 'boot-cmd' },
    { text: 'Blood moon rising...', cls: 'boot-output' },
    { text: 'CRIMSON PROTOCOL ACTIVE', cls: 'boot-ok' },
    { text: '> Lunar anomaly confirmed', cls: 'boot-output' },
    { text: '> Red spectrum: saturated', cls: 'boot-output' },
    { text: '> Shadow index: maximum', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  midnight: [
    { text: '> Starting night shift...', cls: 'boot-cmd' },
    { text: 'Starlight OS v2.0 loaded', cls: 'boot-output' },
    {
      text: '[  OK  ] Midnight protocols active',
      cls: 'boot-ok',
    },
    { text: '> Ambient light: minimal', cls: 'boot-output' },
    { text: '> Focus mode: engaged', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  arctic: [
    { text: '> Defrosting display...', cls: 'boot-cmd' },
    { text: 'Daylight mode activated', cls: 'boot-output' },
    { text: '[  OK  ] Arctic OS ready', cls: 'boot-ok' },
    { text: '> Brightness: optimized', cls: 'boot-output' },
    { text: '> Ice shelf: stable', cls: 'boot-output' },
    { text: '> Clean compile complete', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  gruvbox: [
    { text: 'GNU/Linux booting...', cls: 'boot-cmd' },
    { text: 'vim --servername portfolio', cls: 'boot-output' },
    { text: '[  OK  ] Retro terminal loaded', cls: 'boot-ok' },
    { text: '> :set colorscheme gruvbox', cls: 'boot-cmd' },
    { text: '> Buffer ready', cls: 'boot-output' },
    { text: '> :w saved successfully', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
};

export const themeToasts: Record<ThemeName, ThemeToasts> = {
  hacker: {
    click: [
      '# Firewall bypassed on port 443',
      '> Packet intercepted: 192.168.x.x',
      '$ Buffer overflow in sector 7',
      '# Encryption key rotated: SHA256:a3f82c',
      '> SSH tunnel to darknet established',
      '$ Payload delivered — 0 traces',
      '# Root shell spawned (PID 31337)',
      '> Memory dump: 0xDEADBEEF',
      '$ Brute force: 12,847 combos/sec',
      '# Certificate pinning bypassed',
    ],
    ambient: [
      '[CRON] Scheduled recon scan completed',
      '[ALERT] New device detected on network',
      '[SYNC] Encrypted backup: 100% complete',
      '[MONITOR] Intrusion detection: all clear',
      '[DAEMON] Process health check: nominal',
    ],
  },
  dracula: {
    click: [
      '> The Count approves',
      '# Nocturnal mode active',
      '> Blood bank: replenished',
      '$ Bat sonar: 3 echoes detected',
      '> Cape swirl animation: smooth',
    ],
    ambient: [
      '[NIGHT] Moon phase updated',
      '[CRYPT] Coffin integrity: 100%',
      '[BAT] Sonar sweep complete',
    ],
  },
  nord: {
    click: [
      '> Northern lights detected',
      '# Ice core sample analyzed',
      '> Frost pattern: unique',
      '$ Aurora intensity: 7/10',
      '> Polar wind shift logged',
    ],
    ambient: [
      '[AURORA] Light display active',
      '[TEMP] Arctic readings nominal',
      '[SNOW] Accumulation: 2cm/hr',
    ],
  },
  catppuccin: {
    click: [
      '> Latte art complete',
      '# Comfort mode engaged',
      '> Warm pixels: deployed',
      '$ Cozy level: maximum',
      '> Mocha blend: perfected',
    ],
    ambient: [
      '[BREW] Fresh batch ready',
      '[COZY] Ambient warmth stable',
      '[PIXEL] Pastel palette refreshed',
    ],
  },
  synthwave: {
    click: [
      '> Tape rewound',
      '# Signal boosted to 11',
      '$ Neon circuit: overclocked',
      '> Synth key pressed: C major',
      '> Chrome reflection: maximum',
    ],
    ambient: [
      '[FM] Radio frequency locked',
      '[VHS] Tape playback smooth',
      '[NEON] Grid power: stable',
    ],
  },
  matrix: {
    click: [
      '> Red pill accepted',
      '# Agent detected nearby',
      '$ Glitch in the matrix',
      '> Deja vu — same cat',
      '> Code is raining',
    ],
    ambient: [
      `[MATRIX] Simulation tick #${String(Math.floor(Math.random() * 99999))}`,
      '[AGENT] Patrol route updated',
      '[ORACLE] Prediction logged',
    ],
  },
  bloodmoon: {
    click: [
      '> Lunar anomaly detected',
      '# Eclipse phase complete',
      '$ Crimson wave incoming',
      '> Shadow index: rising',
      '> Blood tide: receding',
    ],
    ambient: ['[ECLIPSE] Next phase in 3h', '[LUNAR] Anomaly stable', '[CRIMSON] Protocol holding'],
  },
  midnight: {
    click: [
      '> Midnight oil burning',
      '# Night mode optimized',
      '$ Star map updated',
      '> Constellation found',
      '> Deep focus achieved',
    ],
    ambient: [
      '[STAR] New constellation mapped',
      '[NIGHT] Ambient noise: minimal',
      '[FOCUS] Productivity: peak',
    ],
  },
  arctic: {
    click: [
      '> Brightness optimized',
      '# Clean compile complete',
      '$ Frost defragmented',
      '> Crystal clarity achieved',
      '> Light mode: pristine',
    ],
    ambient: ['[LIGHT] Display calibrated', '[ICE] Structure: optimal', '[CLEAN] Build successful'],
  },
  gruvbox: {
    click: [
      '> :w saved successfully',
      '# Buffer cleaned',
      '$ :qa! — force quit averted',
      '> Vim macro recorded',
      '> Retro mode: engaged',
    ],
    ambient: [
      '[VIM] Swap file cleaned',
      '[TERM] Shell history saved',
      '[RETRO] CRT warmth optimal',
    ],
  },
};

export const aboutThemes: Record<ThemeName, AboutTheme> = {
  hacker: {
    sectionLabel: '// cat /etc/target',
    filename: 'classified_dossier.sh',
    headerComment: 'CLASSIFIED \u2014 SECURITY CLEARANCE: ROOT',
    echoMessage: '[STATUS] Dossier loaded. Target identified.',
    defaultLang: 'python',
  },
  dracula: {
    sectionLabel: '// cat /castle/resident',
    filename: 'blood_oath_registry.sh',
    headerComment: 'CASTLE DRACUL \u2014 BLOOD OATH REGISTRY',
    echoMessage: '[ETERNAL] Profile immortalized. The night awaits.',
    defaultLang: 'ruby',
  },
  nord: {
    sectionLabel: '// cat /fjord/manifest',
    filename: 'nordic_expedition.sh',
    headerComment: 'NORDIC EXPEDITION \u2014 CREW MANIFEST',
    echoMessage: '[FROST] Manifest loaded. Course set north.',
    defaultLang: 'go',
  },
  catppuccin: {
    sectionLabel: '// cat ~/.config/me',
    filename: 'cozy_profile.sh',
    headerComment: 'CATPPUCCIN BLEND \u2014 DEVELOPER PROFILE',
    echoMessage: '[BREW] Profile steeped. Ready to serve.',
    defaultLang: 'javascript',
  },
  synthwave: {
    sectionLabel: '// LOAD PROFILE.DAT',
    filename: 'neon_profile.dat',
    headerComment: 'SYNTHCORP \u2014 OPERATOR DATAFILE',
    echoMessage: '[NEON] Datafile loaded. Welcome to the grid.',
    defaultLang: 'javascript',
  },
  matrix: {
    sectionLabel: '// cat /dev/construct',
    filename: 'construct_profile.sh',
    headerComment: 'THE MATRIX \u2014 OPERATIVE CONSTRUCT',
    echoMessage: '[SIGNAL] Construct loaded. Follow the white rabbit.',
    defaultLang: 'cpp',
  },
  bloodmoon: {
    sectionLabel: '// cat /blood/pact',
    filename: 'crimson_dossier.sh',
    headerComment: 'BLOOD MOON COVENANT \u2014 DARK REGISTRY',
    echoMessage: '[RITUAL] Dossier sealed in crimson.',
    defaultLang: 'java',
  },
  midnight: {
    sectionLabel: '// cat /cosmos/signal',
    filename: 'stellar_manifest.sh',
    headerComment: 'MIDNIGHT OBSERVATORY \u2014 STELLAR MANIFEST',
    echoMessage: '[COSMIC] Signal decoded. Stars aligned.',
    defaultLang: 'typescript',
  },
  arctic: {
    sectionLabel: '// cat /sys/profile',
    filename: 'engineer_profile.sh',
    headerComment: 'SYSTEM PROFILE \u2014 ENGINEERING RECORD',
    echoMessage: '[SYSTEM] Profile loaded successfully.',
    defaultLang: 'typescript',
  },
  gruvbox: {
    sectionLabel: '// cat /workshop/log',
    filename: 'craftsman_log.sh',
    headerComment: 'WORKSHOP LOG \u2014 MASTER CRAFTSMAN',
    echoMessage: '[CRAFT] Workbench loaded. Tools ready.',
    defaultLang: 'bash',
  },
};

/* ── Theme getters (all use cached getCurrentTheme from state) ── */
export const getThemeConfig = themeGetter(themeConfig);
export const getAboutTheme = themeGetter(aboutThemes);
export const getThemeToasts = themeGetter(themeToasts);
export const getBootMessages = themeGetter(bootMessages);
export const getThemeLogo = themeGetter(themeLogos);
export const getStatusBarConfig = themeGetter(themeStatusBars);
