import type { BootMessage, ThemeName } from '../types';
import { themeGetter } from './core';

export const bootMessages: Record<ThemeName, BootMessage[]> = {
  hacker: [
    { text: '$ uname -a', cls: 'boot-cmd' },
    { text: 'Linux mainframe 6.1.0-kali9 #1 SMP x86_64 GNU/Linux', cls: 'boot-output' },
    { text: '$ sudo systemctl start portfolio.service', cls: 'boot-cmd' },
    { text: '[  OK  ] Started portfolio.service', cls: 'boot-ok' },
    { text: '$ nmap -sS 10.0.0.0/24 --top-ports 5', cls: 'boot-cmd' },
    { text: 'Starting Nmap 7.94 ( https://nmap.org )', cls: 'boot-output' },
    { text: 'PORT    STATE SERVICE', cls: 'boot-output' },
    { text: '22/tcp  open  ssh', cls: 'boot-output' },
    { text: '80/tcp  open  http', cls: 'boot-output' },
    { text: '443/tcp open  https', cls: 'boot-output' },
    { text: '$ ssh -i ~/.ssh/id_rsa root@portfolio', cls: 'boot-cmd' },
    { text: 'Authenticating with public key...', cls: 'boot-output' },
    { text: 'root@portfolio:~# cat /etc/motd', cls: 'boot-cmd' },
    { text: '', cls: '' },
  ],
  dracula: [
    { text: '> Awakening from coffin...', cls: 'boot-cmd' },
    { text: 'Blood type: #BD93F9', cls: 'boot-output' },
    { text: '> Loading nocturnal protocols...', cls: 'boot-cmd' },
    { text: '[  OK  ] Bat signal initialized', cls: 'boot-ok' },
    { text: '> Checking garlic firewall...', cls: 'boot-cmd' },
    { text: 'No threats detected', cls: 'boot-output' },
    { text: '> Moon phase: Full', cls: 'boot-output' },
    { text: '> Vampire.js runtime loaded', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  nord: [
    { text: '> Initializing aurora...', cls: 'boot-cmd' },
    { text: 'Polar winds calibrated', cls: 'boot-output' },
    { text: '> Loading frost interface...', cls: 'boot-cmd' },
    { text: '[  OK  ] Nordic shell ready', cls: 'boot-ok' },
    { text: '> Temperature: -15C', cls: 'boot-output' },
    { text: '> Snowfall density: optimal', cls: 'boot-output' },
    { text: '> Ice core sample analyzed', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  catppuccin: [
    { text: '> Brewing fresh mocha...', cls: 'boot-cmd' },
    { text: 'Warming up the pixels', cls: 'boot-output' },
    { text: '> Loading cozy interface...', cls: 'boot-cmd' },
    { text: '[  OK  ] Comfort mode engaged', cls: 'boot-ok' },
    { text: '> Latte foam: perfect', cls: 'boot-output' },
    { text: '> Ambient warmth: 100%', cls: 'boot-output' },
    { text: '> Pastel palette loaded', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  synthwave: [
    { text: 'LOADING CASSETTE...', cls: 'boot-cmd' },
    { text: '> PLAY SIDE A', cls: 'boot-output' },
    { text: 'NEON SYSTEMS ONLINE', cls: 'boot-ok' },
    { text: '> Retrowave frequency locked', cls: 'boot-output' },
    { text: '> DeLorean flux capacitor: READY', cls: 'boot-output' },
    { text: '> Synthesizer calibrated', cls: 'boot-output' },
    { text: '> Chrome reflections: MAX', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  matrix: [
    { text: 'Wake up, Neo...', cls: 'boot-cmd' },
    { text: 'The Matrix has you...', cls: 'boot-output' },
    { text: 'Follow the white rabbit.', cls: 'boot-output' },
    { text: '> Knock, knock.', cls: 'boot-cmd' },
    { text: 'Loading construct...', cls: 'boot-output' },
    { text: '[  OK  ] Red pill accepted', cls: 'boot-ok' },
    { text: '> Agent detection: scanning', cls: 'boot-output' },
    { text: '> Zion mainframe connected', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  bloodmoon: [
    { text: '> Eclipse detected...', cls: 'boot-cmd' },
    { text: 'Blood moon rising...', cls: 'boot-output' },
    { text: 'CRIMSON PROTOCOL ACTIVE', cls: 'boot-ok' },
    { text: '> Lunar anomaly confirmed', cls: 'boot-output' },
    { text: '> Red spectrum: saturated', cls: 'boot-output' },
    { text: '> Shadow index: maximum', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  midnight: [
    { text: '> Starting night shift...', cls: 'boot-cmd' },
    { text: 'Starlight OS v2.0 loaded', cls: 'boot-output' },
    { text: '[  OK  ] Midnight protocols active', cls: 'boot-ok' },
    { text: '> Ambient light: minimal', cls: 'boot-output' },
    { text: '> Focus mode: engaged', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  arctic: [
    { text: '> Defrosting display...', cls: 'boot-cmd' },
    { text: 'Daylight mode activated', cls: 'boot-output' },
    { text: '[  OK  ] Arctic OS ready', cls: 'boot-ok' },
    { text: '> Brightness: optimized', cls: 'boot-output' },
    { text: '> Ice shelf: stable', cls: 'boot-output' },
    { text: '> Clean compile complete', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  gruvbox: [
    { text: 'GNU/Linux booting...', cls: 'boot-cmd' },
    { text: 'vim --servername portfolio', cls: 'boot-output' },
    { text: '[  OK  ] Retro terminal loaded', cls: 'boot-ok' },
    { text: '> :set colorscheme gruvbox', cls: 'boot-cmd' },
    { text: '> Buffer ready', cls: 'boot-output' },
    { text: '> :w saved successfully', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  cyberpunk: [
    { text: 'NCPD SYSTEM v4.7', cls: 'boot-cmd' },
    { text: '> Cyberware diagnostics: PASS', cls: 'boot-output' },
    { text: '> Neural link: STABLE', cls: 'boot-ok' },
    { text: '> Scanning local ICE...', cls: 'boot-cmd' },
    { text: 'No intrusion detected', cls: 'boot-output' },
    { text: '> Connecting to Arasaka subnet', cls: 'boot-output' },
    { text: '> Bandwidth: 12 TB/s', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  nebula: [
    { text: 'Hubble Relay v3.1', cls: 'boot-cmd' },
    { text: '> Spectrometer: CALIBRATED', cls: 'boot-output' },
    { text: '[  OK  ] Nebula NGC-7023: LOCKED', cls: 'boot-ok' },
    { text: '> Telescope alignment verified', cls: 'boot-output' },
    { text: '> Deep field imaging: ACTIVE', cls: 'boot-output' },
    { text: '> Signal strength: optimal', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  solarized: [
    { text: 'solarized-shell v1.0', cls: 'boot-cmd' },
    { text: '> Gamma correction: APPLIED', cls: 'boot-output' },
    { text: '[  OK  ] Display: CALIBRATED', cls: 'boot-ok' },
    { text: '> Color temperature: 6500K', cls: 'boot-output' },
    { text: '> Contrast ratio: optimal', cls: 'boot-output' },
    { text: '> Environment ready', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  rosepine: [
    { text: 'ros\u00E9-garden v2.0', cls: 'boot-cmd' },
    { text: '> Bloom cycle: SPRING', cls: 'boot-output' },
    { text: '[  OK  ] Petal count: ABUNDANT', cls: 'boot-ok' },
    { text: '> Soil moisture: optimal', cls: 'boot-output' },
    { text: '> Sunlight exposure: gentle', cls: 'boot-output' },
    { text: '> Garden gate open', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
  monokai: [
    { text: 'sublime-shell v4.0', cls: 'boot-cmd' },
    { text: '> Syntax highlighting: LOADED', cls: 'boot-output' },
    { text: '[  OK  ] Package control: READY', cls: 'boot-ok' },
    { text: '> Color scheme: Monokai', cls: 'boot-cmd' },
    { text: '> Minimap: enabled', cls: 'boot-output' },
    { text: '> All plugins loaded', cls: 'boot-output' },
    { text: '', cls: '' },
  ],
};

export const getBootMessages = themeGetter(bootMessages);
