import { getCurrentTheme } from '../state';
import type { ThemeConfig, ThemeName } from '../types';

export { getCurrentTheme } from '../state';

export function themeGetter<T>(map: Record<ThemeName, T>): (theme?: ThemeName) => T {
  return (theme) => map[theme ?? getCurrentTheme()] ?? map.hacker;
}

const baseTheme: ThemeConfig = {
  canvasEffect: 'particles',
  hasMatrixRain: false,
  hasCRT: false,
  screenEffect: 'none',
  hasHackerLog: false,
  hasCursor: false,
  particleColor: 'rgba(255, 255, 255, ',
  bootBg: '#0a0e14',
  navBg: 'transparent',
  heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  heroTiming: { flicker: 60, resolve: 110 },
};

export const themeConfig: Record<ThemeName, ThemeConfig> = {
  hacker: {
    ...baseTheme,
    hasMatrixRain: true,
    hasCRT: true,
    screenEffect: 'glitch',
    hasHackerLog: true,
    hasCursor: 'crosshair',
    particleColor: 'rgba(91, 205, 236, ',
    matrixColor: 'rgba(0, 191, 191, 0.6)',
    matrixBg: 'rgba(10, 14, 20, 0.06)',
    navBg: 'rgba(13, 17, 23, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789$@#!%&*?',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  dracula: {
    ...baseTheme,
    canvasEffect: 'purpleParticles',
    screenEffect: 'fogWisps',
    hasCursor: 'dot',
    particleColor: 'rgba(189, 147, 249, ',
    bootBg: '#1e1b2e',
    navBg: 'rgba(40, 42, 54, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ†‡§¶∞ΩΨ',
  },
  nord: {
    ...baseTheme,
    canvasEffect: 'snowfall',
    screenEffect: 'auroraShimmer',
    particleColor: 'rgba(136, 192, 208, ',
    bootBg: '#242933',
    navBg: 'rgba(46, 52, 64, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ·:;_=-~',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  catppuccin: {
    ...baseTheme,
    canvasEffect: 'bubbles',
    screenEffect: 'pastelBloom',
    hasCursor: 'dot',
    particleColor: 'rgba(203, 166, 247, ',
    bootBg: '#181825',
    navBg: 'rgba(30, 30, 46, ',
    heroGlyphs: 'abcdefghijklmnopqrstuvwxyz~*.:+',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  synthwave: {
    ...baseTheme,
    canvasEffect: 'retroGrid',
    hasCRT: true,
    screenEffect: 'vhsDistortion',
    hasCursor: 'dot',
    particleColor: 'rgba(255, 46, 151, ',
    bootBg: '#120a1e',
    navBg: 'rgba(26, 16, 40, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ▓░▒█01',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  matrix: {
    ...baseTheme,
    hasMatrixRain: true,
    hasCRT: true,
    screenEffect: 'glitch',
    hasCursor: 'crosshair',
    particleColor: 'rgba(0, 255, 65, ',
    matrixColor: 'rgba(0, 255, 65, 0.8)',
    matrixBg: 'rgba(0, 0, 0, 0.05)',
    bootBg: '#050505',
    navBg: 'rgba(10, 10, 10, ',
    heroGlyphs: 'アイウエオカキクケコサシスセソ01',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  bloodmoon: {
    ...baseTheme,
    canvasEffect: 'bloodRain',
    screenEffect: 'bloodDrip',
    hasCursor: 'dot',
    particleColor: 'rgba(255, 0, 64, ',
    bootBg: '#080104',
    navBg: 'rgba(13, 2, 8, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ†‡Ψ∞Ω◆',
    heroTiming: { flicker: 50, resolve: 90 },
  },
  midnight: {
    ...baseTheme,
    canvasEffect: 'starfield',
    screenEffect: 'shootingStar',
    particleColor: 'rgba(123, 115, 255, ',
    bootBg: '#0a0a12',
    navBg: 'rgba(15, 15, 26, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ★✦⊹∗⋆',
  },
  arctic: {
    ...baseTheme,
    canvasEffect: 'lightDust',
    screenEffect: 'iceCrack',
    particleColor: 'rgba(3, 105, 161, ',
    bootBg: '#e0f2fe',
    navBg: 'rgba(219, 234, 254, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  gruvbox: {
    ...baseTheme,
    canvasEffect: 'fireflies',
    screenEffect: 'tvStatic',
    hasCRT: true,
    hasCursor: 'dot',
    particleColor: 'rgba(250, 189, 47, ',
    bootBg: '#1d2021',
    navBg: 'rgba(40, 40, 40, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ>|/-_=+[]',
  },
  cyberpunk: {
    ...baseTheme,
    canvasEffect: 'neonSparks',
    hasCRT: true,
    screenEffect: 'hologramFlicker',
    hasCursor: 'crosshair',
    particleColor: 'rgba(255, 215, 0, ',
    bootBg: '#08080f',
    navBg: 'rgba(10, 10, 18, ',
    heroGlyphs: '$#@!><_{}[]|\\',
    heroTiming: { flicker: 40, resolve: 80 },
  },
  nebula: {
    ...baseTheme,
    canvasEffect: 'cosmicDust',
    screenEffect: 'nebulaPulse',
    hasCursor: 'dot',
    particleColor: 'rgba(224, 64, 251, ',
    bootBg: '#080010',
    navBg: 'rgba(11, 0, 20, ',
    heroGlyphs: '\u2605\u2726\u22B9\u2217\u22C6\u263E\u2643\u2644',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  solarized: {
    ...baseTheme,
    canvasEffect: 'lightDust',
    screenEffect: 'none',
    particleColor: 'rgba(38, 139, 210, ',
    bootBg: '#001e26',
    navBg: 'rgba(0, 43, 54, ',
    heroGlyphs: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  rosepine: {
    ...baseTheme,
    canvasEffect: 'fireflies',
    screenEffect: 'pastelBloom',
    hasCursor: 'dot',
    particleColor: 'rgba(234, 154, 151, ',
    bootBg: '#131120',
    navBg: 'rgba(25, 23, 36, ',
    heroGlyphs: '~*.+:;abcdefghijklmnopqrstuvwxyz',
    heroTiming: { flicker: 80, resolve: 140 },
  },
  monokai: {
    ...baseTheme,
    canvasEffect: 'embers',
    hasCRT: true,
    screenEffect: 'glitch',
    hasCursor: 'dot',
    particleColor: 'rgba(166, 226, 46, ',
    bootBg: '#1e1f1a',
    navBg: 'rgba(39, 40, 34, ',
    heroGlyphs: '{}[]()<>;:ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    heroTiming: { flicker: 50, resolve: 90 },
  },
};

export const getThemeConfig = themeGetter(themeConfig);
