import type { ThemeName } from '../types';

export const themeTypewriterTexts: Record<ThemeName, string[]> = {
  hacker: [
    '> Senior Software Engineer',
    '> Bypassing firewall protocols...',
    '> Ruby on Rails — exploit deployed',
    '> Node.js injection payload ready',
    '> React components compromised',
    '> AWS infrastructure infiltrated',
    '> PostgreSQL data exfiltrated',
    '> Docker containers breached',
    '> GraphQL schema enumerated',
    '> TypeScript zero-day compiled',
    '> Redis cache poisoned',
    '> Open source rootkits published',
    '> Access granted. Welcome back.',
  ],
  dracula: [
    '> Senior Software Engineer',
    '> The mass darkness stirs...',
    '> Ruby on Rails — immortal framework',
    '> Node.js event loop never sleeps',
    '> React — reborn with every render',
    '> AWS clouds part for the count',
    '> PostgreSQL — eternal data vault',
    '> Docker coffins sealed tight',
    '> GraphQL queries from the crypt',
    '> TypeScript — type-safe in the dark',
    '> Redis — blood-red cache layer',
    '> Open source from Transylvania',
    '> The count welcomes you.',
  ],
  nord: [
    '> Senior Software Engineer',
    '> Calm as the northern fjords...',
    '> Ruby on Rails — steady as the fjords',
    '> Node.js streams flow like glacial rivers',
    '> React — minimal, purposeful UI',
    '> AWS — aurora-lit infrastructure',
    '> PostgreSQL — frozen solid data',
    '> Docker — containerized serenity',
    '> GraphQL — clean, structured queries',
    '> TypeScript — precise and composed',
    '> Redis — swift as polar winds',
    '> Open source from the quiet north',
    '> Welcome to the quiet north.',
  ],
  catppuccin: [
    '> Senior Software Engineer',
    '> Brewing something warm~',
    '> Ruby on Rails with a warm latte~',
    '> Node.js — sweet async treats',
    '> React — cozy component library',
    '> AWS — cloud-soft infrastructure~',
    '> PostgreSQL — freshly roasted data',
    '> Docker — neatly packed bento boxes',
    '> GraphQL — a perfectly layered cake',
    '> TypeScript — types with sprinkles~',
    '> Redis — quick espresso cache',
    '> Open source with love and pastels',
    '> Pull up a chair, stay a while~',
  ],
  synthwave: [
    '> Senior Software Engineer',
    '> Booting neon grid sequence...',
    '> Ruby on Rails at light speed',
    '> Node.js at 88 miles per hour',
    '> React — rendering the retro future',
    '> AWS — neon-lit cloud highways',
    '> PostgreSQL — data in the fast lane',
    '> Docker — chrome-plated containers',
    '> GraphQL — laser-guided queries',
    '> TypeScript — synth-typed perfection',
    '> Redis — turbo-cached at 120bpm',
    '> Open source from the neon arcade',
    '> Welcome to the grid, rider.',
  ],
  matrix: [
    '> Senior Software Engineer',
    '> Wake up... the code has you.',
    '> Ruby on Rails — follow the white rabbit',
    '> Node.js — there is no callback',
    '> React — the construct is loading',
    '> AWS — the machine city awaits',
    '> PostgreSQL — the Oracle knows',
    '> Docker — pods in the Matrix',
    '> GraphQL — querying the source code',
    '> TypeScript — the One true type system',
    '> Redis — red pill cache activated',
    '> Open source — free your mind',
    '> There is no spoon. Only functions.',
  ],
  bloodmoon: [
    '> Senior Software Engineer',
    '> The hunt for perfect code begins...',
    '> Ruby on Rails — forged in crimson fire',
    '> Node.js — relentless event predator',
    '> React — components sharp as fangs',
    '> AWS — infrastructure under blood skies',
    '> PostgreSQL — data sealed in obsidian',
    '> Docker — hunting in packs',
    '> GraphQL — tracking every query',
    '> TypeScript — precision of the kill',
    '> Redis — bloodhound-fast cache',
    '> Open source — unleash the pack',
    '> The eclipse reveals all.',
  ],
  midnight: [
    '> Senior Software Engineer',
    '> Charting the code nebula...',
    '> Ruby on Rails — orbiting at warp speed',
    '> Node.js — signals from deep space',
    '> React — rendering distant galaxies',
    '> AWS — cosmic cloud infrastructure',
    '> PostgreSQL — stellar data clusters',
    '> Docker — orbital containers deployed',
    '> GraphQL — scanning the star charts',
    '> TypeScript — astro-typed precision',
    '> Redis — light-speed cache relay',
    '> Open source across the galaxy',
    '> Transmission received. Welcome aboard.',
  ],
  arctic: [
    '> Senior Software Engineer',
    '> Initializing clean workspace...',
    '> Ruby on Rails — clean, reliable, fast',
    '> Node.js — efficient async workflows',
    '> React — modular component architecture',
    '> AWS — scalable cloud solutions',
    '> PostgreSQL — robust data management',
    '> Docker — reproducible environments',
    '> GraphQL — precise API design',
    '> TypeScript — enterprise-grade types',
    '> Redis — high-performance caching',
    '> Open source — community-driven code',
    "> Welcome. Let's build something great.",
  ],
  gruvbox: [
    '> Senior Software Engineer',
    '> Booting vintage terminal...',
    '> Ruby on Rails — classic and battle-tested',
    '> Node.js — old reliable, new tricks',
    '> React — components from the golden age',
    '> AWS — mainframe-grade cloud power',
    "> PostgreSQL — rock-solid since '96",
    '> Docker — containers, the unix way',
    '> GraphQL — querying like a sysadmin',
    '> TypeScript — strongly typed, old school',
    '> Redis — cache at the speed of CRT',
    '> Open source — the hacker ethic lives',
    '> Connection established. Welcome back.',
  ],
  cyberpunk: [
    '> Senior Software Engineer',
    '> Jacking into the net...',
    '> Ruby on Rails — chrome-plated backend',
    '> Node.js — neural link async pipeline',
    '> React — holographic UI components',
    '> AWS — megacorp cloud grid',
    '> PostgreSQL — data vault in Night City',
    '> Docker — armored containers deployed',
    '> GraphQL — braindance data streams',
    '> TypeScript — cyberdeck firmware loaded',
    '> Redis — quickhack cache injected',
    '> Open source from the combat zone',
    '> Welcome to Night City, choom.',
  ],
  nebula: [
    '> Senior Software Engineer',
    '> Scanning the cosmos...',
    '> Ruby on Rails — orbital framework relay',
    '> Node.js — signals across the void',
    '> React — rendering nebula clusters',
    '> AWS — interstellar cloud network',
    '> PostgreSQL — data locked in dark matter',
    '> Docker — pods in stable orbit',
    '> GraphQL — querying star catalogs',
    '> TypeScript — spectrum-calibrated types',
    '> Redis — light-speed photon cache',
    '> Open source from deep space',
    '> Signal acquired. Welcome, stargazer.',
  ],
  solarized: [
    '> Senior Software Engineer',
    '> Calibrating display...',
    '> Ruby on Rails — balanced and elegant',
    '> Node.js — precise async operations',
    '> React — clean component hierarchy',
    '> AWS — well-structured cloud setup',
    '> PostgreSQL — organized data layers',
    '> Docker — reproducible builds',
    '> GraphQL — structured query design',
    '> TypeScript — properly typed codebase',
    '> Redis — efficient caching strategy',
    '> Open source — thoughtful contributions',
    '> Display calibrated. Welcome.',
  ],
  rosepine: [
    '> Senior Software Engineer',
    '> Tending the digital garden...',
    '> Ruby on Rails — roots run deep',
    '> Node.js — evergreen async blooms',
    '> React — petals of composable UI',
    '> AWS — cloud canopy overhead',
    '> PostgreSQL — seeds of structured data',
    '> Docker — greenhouse containers',
    '> GraphQL — branching query paths',
    '> TypeScript — thorns of type safety',
    '> Redis — morning dew cache',
    '> Open source — cultivated with care',
    '> The garden welcomes you.',
  ],
  monokai: [
    '> Senior Software Engineer',
    '> Loading syntax highlighting...',
    '> Ruby on Rails — syntax-highlighted perfection',
    '> Node.js — event loop in vivid color',
    '> React — components in bold strokes',
    '> AWS — infrastructure as highlighted code',
    '> PostgreSQL — queries in living color',
    '> Docker — containerized with style',
    '> GraphQL — schemas painted bright',
    '> TypeScript — every type has a color',
    '> Redis — cached in electric green',
    '> Open source — written in Monokai',
    '> Editor ready. Start typing.',
  ],
};
